INSERT INTO Kluby (Skrot, Nazwa) VALUES
('WOL', 'UKS Albatros Wolin'),
('SPO', 'Sport Vita Ski&Sail'),
('OCC', 'Ocean Challenge Yacht Club'),
('KKZ', 'Kościański Klub Żeglarski'),
('NIE', 'KS Marina Niesulice'),
('SLA', 'Slava Racing'),
('GAR', 'KW Garland'),
('YCB', 'Yacht Club Białołęka'),
('NAV', 'UKS Navigo'),
('JSG', 'Jachtklub Stoczni Gdańskiej'),
('PJK', 'Stowarzyszenie PPJK'),
('YS2', 'Yacht Club Sopot 2'),
('ODY', 'Odyssey Sailing Club'),
('HAL', 'Klub Żeglarski HALS Gostynin'),
('GRP', 'Grupa Regatowa Powidz'),
('POW', 'SKŻ Powidz'),
('MEW', 'Małe Elektrownie Wodne Micro Class'),
('ETI', 'Etisoft 2KMM Sailing Team');
