INSERT INTO Kluby (Skrot, Nazwa) VALUES
('YCG', 'Yacht Club Gdańsk'),
('POG', 'Pogoń Szczecin'),
('YCS', 'Yacht Club Sopot'),
('YKS', 'YKP Szczecin'),
('YKP', 'YKP Gdynia'),
('WAT', 'AZS WAT Warszawa'),
('WRO', 'UKS Żeglarz Wrocław'),
('NSO', 'Nowy Sztynort Osada Wolności Giżycka Grupa Regatowa'),
('HRM', 'HRM Racing'),
('LEG', 'Legia Warszawa'),
('PGR', 'AZS Politechnika Gdańska'),
('AWF', 'AZS AWFiS Gdańsk'),
('YKL', 'Lubelskie YKP Lublin'),
('RSR', 'On Lemon Rockstars Racing'),
('SZT', 'Sztorm Grupa Warszawa'),
('ISK', 'KS Iskra AMW Gdynia'),
('OKZ', 'Olsztyński Klub Żeglarski'),
('POL', 'Polsporty Sailing');
