INSERT INTO Kluby (Skrot, Nazwa) VALUES
('WAT', 'AZS WAT Warszawa'),
('AWF', 'AZS AWFiS Gdańsk'),
('YSZ', 'YKP Szczecin'),
('WRO', 'UKS Żeglarz Wrocław'),
('HRM', 'HRM Racing Yacht Club Gdańsk'),
('NIE', 'KS Marina Niesulice'),
('GSP', 'Garden Space Sailing Club'),
('GRP', 'TFE Grupa Regatowa Powidz'),
('NAV', 'UKS Navigo'),
('KKZ', 'Kościański Klub Żeglarski'),
('AKA', 'Akademia Żeglarstwa w Środzie Wielkopolskiej'),
('LE2', 'Legia Warszawa 2'),
('YS2', 'Yacht Club Sopot 2'),
('OCC', 'Ocean Challenge Yacht Club Ladies Sailing Team'),
('LAS', 'RKS Lasery Zegrze'),
('RBP', 'Regatta Business Poland'),
('ETI', 'Etisoft Sailing Team Gliwice'),
('POW', 'SKŻ Powidz');
