INSERT INTO Kluby (Skrot, Nazwa) VALUES
('YKP', 'Yacht Klub Polski Gdynia'),
('YCG', 'Yacht Club Gdańsk'),
('LEG', 'Legia Warszawa'),
('OKZ', 'Olsztyński Klub Żeglarski'),
('POG', 'SEJK Pogoń Szczecin'),
('SZT', 'Sztorm Grupa'),
('ISK', 'KS Iskra AMW Gdynia'),
('PGR', 'AZS Politechnika Gdańska'),
('GIZ', 'Giżycka Grupa Regatowa'),
('GAR', 'KW Garland Gliwice'),
('SPO', 'Sport Vita Ski&Sail'),
('JMZ', 'JK Między Żaglami'),
('YCS', 'Yacht Club Sopot'),
('ODY', 'Odyssey Sailing Club'),
('PJK', 'Stowarzyszenie PPJK'),
('DZY', 'PŻKS Dżygit Białystok'),
('JSG', 'Jachtklub Stoczni Gdańskiej'),
('WOL', 'UKS Albatros Wolin');
