INSERT INTO Kluby (Skrot, Nazwa) VALUES
('ISK', 'KS Iskra AMW Gdynia'),
('ONB', 'Onboard'),
('SZT', 'Sztorm Grupa Warszawa'),
('NIE', 'KS Marina Niesulice'),
('GAR', 'KW Garland Gliwice'),
('MEC', 'Port Mechelinki'),
('BSA', 'BSA Flota Gdynia'),
('YCB', 'Yacht Club Białołęka'),
('SLA', 'Slava Racing'),
('OKZ', 'Olsztyński Klub Żeglarski'),
('JSG', 'MOWI Jachtklub Stoczni Gdańskiej'),
('NAV', 'UKS Navigo'),
('HAL', 'KŻ Hals Gostynin'),
('YS2', 'Yacht Club Sopot 2'),
('YKW', 'YKP Warszawa'),
('PJK', 'Puchar Polski Jachtów Kabinowych'),
('ODY', 'Odyssey Sailing Club'),
('ETI', 'Etisoft 2KMM Sailing Team');
