INSERT INTO liga_Kluby (Skrot, Nazwa) VALUES
('YCS', 'Yacht Club Sopot'),
('NSO', 'Nowy Sztynort Osada Wolności GGR'),
('YCG', 'Yacht Club Gdańsk'),
('POG', 'Pogoń Szczecin'),
('HRM', 'HRM Racing'),
('YKP', 'YKP Gdynia'),
('SPO', 'Sport Vita Ski & Sail'),
('WAT', 'AZS WAT Warszawa'),
('RSR', 'Rockstars Racing'),
('YKS', 'YKP Szczecin'),
('YKL', 'Lubelskie YKP Lublin'),
('LEG', 'Legia Warszawa'),
('WRO', 'FinGo Capital UKS Żeglarz Wrocław'),
('AWF', 'AZS AWFiS Gdańsk'),
('WOL', 'UKS Albatros Wolin'),
('OCC', 'Ocean Challenge Sailing Club'),
('PGR', 'AZS Politechnika Gdańska'),
('KKZ', 'Kościański Klub Żeglarski');
