INSERT INTO Kluby (Skrot, Nazwa) VALUES
('JKS', 'Jacht Klub Sztynort'),
('TBD', 'The Barking Dogs'),
('TXT', 'TEXET Sailing Team'),
('SEN', 'SEN Yachts Olsztyn'),
('SCO', 'Stripes & Co'),
('MKŻ', 'Mazurski Klub Żeglarski'),
('SOS', 'Sosnowski i przyjaciele'),
('RST', 'RITS Sailing Team'),
('SOL', 'KS Puchar Soliny'),
('KSW', 'KSW Baltic Dziwnów'),
('YZ2', 'YKP Szczecin 2'),
('SBU', 'SBU Yacht Racing Team'),
('ZEF', 'Zefir-Drakkar Poraj'),
('JEP', 'Joker Pik'),
('POW', 'SKŻ Powidz'),
('HOR', 'KŻ Horn Kraków'),
('FJS', 'Fujitsu Sailing Team'),
('WEE', 'Wydział Elektryczny PW');
