INSERT INTO Kluby (Skrot, Nazwa) VALUES
('RSR', 'Rockstars Racing'),
('HRM', 'HRM Racing'),
('YKL', 'Lubelskie YKP Lublin'),
('POL', 'Polsporty Sailing'),
('KKZ', 'Kościański Klub Żeglarski'),
('AKA', 'Akademia Żeglarstwa w Środzie Wielkopolskiej'),
('YS2', 'Yacht Club Sopot 2'),
('OCC', 'Ocean Challenge Yacht Club'),
('PJK', 'Stowarzyszenie PPJK'),
('JSG', 'Jachtklub Stoczni Gdańskiej'),
('NAV', 'Interdoor UKS Navigo'),
('NIE', 'KS Marina Niesulice'),
('SLA', 'Slava Racing'),
('DZY', 'PŻKS Dżygit Białystok'),
('GRP', 'Grupa Regatowa Powidz'),
('ETI', 'Etisoft 2KMM Sailing Team'),
('WOL', 'UKS Albatros Wolin'),
('LAS', 'Lasery Zegrze');
