INSERT INTO Kluby (Skrot, Nazwa) VALUES
('BLX', 'Balex YKP Gdynia'),
('YCG', 'Yacht Club Gdańsk'),
('LEG', 'Legia Warszawa'),
('POG', 'Pogoń Szczecin'),
('WAT', 'AZS WAT Warszawa'),
('AWF', 'AZS AWFiS Gdańsk'),
('JNG', 'Junga Gdynia Olsztyński Klub Żeglarski'),
('YKS', 'YKP Szczecin'),
('WRO', 'UKS Żeglarz Wrocław'),
('ISK', 'KS Iskra AMW Gdynia'),
('YCS', 'Yacht Club Sopot'),
('PGR', 'AZS Politechnika Gdańska'),
('SZT', 'Sztorm Grupa'),
('GGR', 'GGR Nowy Sztynort Osada Wolności'),
('SPO', 'Sport Vita Ski&Sail'),
('YCB', 'Yacht Club Białołęka'),
('GAR', 'Miasto Gliwice KW Garland'),
('ODY', 'Odyssey Sailing Club');
